


call pathogen#infect()
set nocompatible


filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'rodnaph/vim-color-schemes'

Bundle 'vim-scripts/VimClojure'

Bundle 'tpope/vim-endwise'

Bundle 'tpope/vim-fugitive'

Bundle 'Lokaltog/powerline'



set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

if has('gui_running')
	syntax enable
	set background=dark
	colorscheme solarized
endif

set runtimepath^=~/.vim/bundle/ctrlp.vim

syntax on

set hlsearch

set number

filetype plugin indent on
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
